name: Workflow frontend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload coverage report
        if: success() && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  lint:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint  # Assuming you have a lint script in your package.json

  security-check:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run security audit
        run: npm audit --audit-level=high

  notify:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send failure email notification via MailerLite
        run: |
          # Define email content
          SUBJECT="GitHub Actions Job Failed"
          BODY="The GitHub Actions job has failed in the repository: ${{ github.repository }}. For details, check the actions logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Send email using MailerLite API
          curl -X POST https://api.mailerlite.com/api/v2/email/send \
            -H "Content-Type: application/json" \
            -H "X-MailerLite-ApiKey: ${{ secrets.MAILERLITE_API_KEY }}" \
            -d '{
              "from": {
                "email": "karin.lesnik@student.um.si",
                "name": "GitHub Actions"
              },
              "to": [
                {
                  "email": "karin.lesnik@student.um.si",
                  "name": "Karin Poprijan"
                }
              ],
              "subject": "'$SUBJECT'",
              "body": "'$BODY'",
              "type": "text"
            }'